server:
  port: 8080
  servlet:
    context-path: /study

spring:
    # 配置启用的活动profile
    profiles:
          active: dev
    datasource:
         name: test
         url: jdbc:mysql://192.168.18.129:3306/study
         username: root
         password: 11100247
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.jdbc.Driver
         filters: stat
         maxActive: 20
         initialSize: 1
         maxWait: 60000
         minIdle: 1
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: select 'x'
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedStatements: true
         maxOpenPreparedStatements: 20
         # 设置favicon
    mvc:
        favicon:
          enabled: false
          #----------- charset-----
    http:
        encoding:
          charset: UTF-8
          enabled: true
          force: true

    redis:
      host: 192.168.18.131 #redis 服务器
      password:   #redis 密码
      port: 6379 #redis 端口
      lettuce:
        pool:
          max-idle: 30
          max-active: 30
          min-idle: 0
          max-wait: -1ms

mybatis:
    mapper-locations: classpath:mybatis/*.xml
    type-aliases-package: com.example.studyspringboot.dto

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


 # 运行时可以在控制台查看  启用和未启用的配置报告查看
debug: true



